export const commonLocalEn = {

    'reset': 'Reset',
    'save': 'Save',
    'update': 'Update',
    'search': 'Search',
    'sl': 'Sl',
    'action': 'Action',
    'status': 'Status',
    'upload': 'Upload',
    'cancel': 'Cancel',
    'close': 'Close',
    'submit': 'Submit',
    'noResultFound': 'No result Found',
    'noDataMatchingTheFilter': 'No search result',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'print': 'Print',
    'download': 'Download',
    'active': 'Active',
    'selectOne': 'Select',
    'select': 'Select',
    'addNew': 'Add New',
    'viewList': 'View List',
    'returnToList': 'Return To List',
    'back': 'Back',
    'report': 'Report',
    'details': 'Details',
};
