export const commonLocalBn = {

    'reset': 'মুছুন',
    'save': 'সেভ',
    'update': 'আপডেট',
    'search': 'অনুসন্ধান',
    'sl': 'ক্রমিক',
    'action': 'অ্যাকশন',
    'status': 'স্ট্যাটাস',
    'upload': 'আপলোড',
    'cancel': 'বাতিল',
    'close': 'বন্ধ',
    'submit': 'সাবমিট',
    'add': 'যোগ করুন',
    'print': 'প্রিন্ট',
    'download': 'ডাউনলোড',
    'noResultFound': 'কোন ফলাফল পাওয়া যায়নি',
    'noDataMatchingTheFilter': 'অনুসন্ধানটির কোনও ফলাফল নেই ',
    'delete': 'ডিলিট',
    'edit': 'এডিট',
    'active': 'এক্টিভ',
    'selectOne': 'নির্বাচন করুন',
    'select': 'নির্বাচন করুন',
    'addNew': 'যুক্ত করুন',
    'viewList': 'তালিকা দেখুন',
    'returnToList': 'তালিকায় ফিরুন',
    'back': 'পেছনে',
    'report': 'রিপোর্ট',
    'details': 'বিস্তারিত',
};
